CREATE DATABASE IF NOT EXISTS sensor;
USE sensor;

CREATE TABLE IF NOT EXISTS bh1750 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date DATE DEFAULT CURRENT_DATE,
    time TIME DEFAULT CURRENT_TIME,
    light FLOAT
)
